unique_lead = {
    "ORIGINE_LEAD" : "Formulaire Lead Add", 
    "SOURCE_LEAD" : "Olark Chat", 
    "NIVEAU_LEAD" : "Lead potentiel",
    "QUALITE_LEAD" : "Pourrait être pertinent", 
    "CONTACT_PAR_MAIL" : "Non", 
    "CONTACT_PAR_TELEPHONE" : "Non",
    "STATUT_ACTUEL" : "Sans emploi", 
    "NB_VISITES" : 0, 
    "DUREE_SUR_SITEWEB" : 0,
    "NB_PAGES_VUES_PAR_VISITE" : 0, 
    "DERNIERE_ACTIVITE" : "Email ouvert",
    "DERNIERE_ACTIVITE_NOTABLE" : "Select", 
    "PAYS" : "France", 
    "VILLE" : "Paris", 
    "SPECIALISATION" : "Marketing Management", 
    "TAGS" : "Ne pas suivre de formation continue",
    "INDEX_ACTIVITE" : "Moyen", 
    "INDEX_PROFIL" : "Moyen", 
    "SCORE_ACTIVITE" : 15.0, 
    "SCORE_PROFIL" : 15.0,
    "ANNONCE_VUE" : "Non", 
    "MAGAZINE" : "Non", 
    "ARTICLE_JOURNAL" : "Non", 
    "FORUM" : "Non", 
    "JOURNAUX" : "Non",
    "PUB_DIGITALE" : "Non", 
    "RECOMMANDATION" : "Non",
    "C_ENT_PARLER_NS" : "Non",
    "SOUH_TU_REC_INFOS" : "Non",
    "SOUH_REC_MAJ_PROG" : "Non",
    "SOUH_REC_MAJ_MP" : "Non",
    "SOUH_PAYER_CHEQUE" : "Non",
    "SOUH_REC_COPIE_LB" : "Non"
}


multiple_lead = {
    "1" : {
        "ORIGINE_LEAD" : "Formulaire Lead Add", 
        "SOURCE_LEAD" : "Olark Chat", 
        "NIVEAU_LEAD" : "Lead potentiel",
        "QUALITE_LEAD" : "Pourrait être pertinent", 
        "CONTACT_PAR_MAIL" : "Non", 
        "CONTACT_PAR_TELEPHONE" : "Non",
        "STATUT_ACTUEL" : "Sans emploi", 
        "NB_VISITES" : 10, 
        "DUREE_SUR_SITEWEB" : 0,
        "NB_PAGES_VUES_PAR_VISITE" : 10, 
        "DERNIERE_ACTIVITE" : "Email ouvert",
        "DERNIERE_ACTIVITE_NOTABLE" : "Select", 
        "PAYS" : "France", 
        "VILLE" : "Paris", 
        "SPECIALISATION" : "Marketing Management", 
        "TAGS" : "Ne pas suivre de formation continue",
        "INDEX_ACTIVITE" : "Moyen", 
        "INDEX_PROFIL" : "Moyen", 
        "SCORE_ACTIVITE" : 15.0, 
        "SCORE_PROFIL" : 15.0,
        "ANNONCE_VUE" : "Non", 
        "MAGAZINE" : "Non", 
        "ARTICLE_JOURNAL" : "Non", 
        "FORUM" : "Non", 
        "JOURNAUX" : "Non",
        "PUB_DIGITALE" : "Non", 
        "RECOMMANDATION" : "Non",
        "C_ENT_PARLER_NS" : "Non",
        "SOUH_TU_REC_INFOS" : "Non",
        "SOUH_REC_MAJ_PROG" : "Non",
        "SOUH_REC_MAJ_MP" : "Non",
        "SOUH_PAYER_CHEQUE" : "Non",
        "SOUH_REC_COPIE_LB" : "Non"
    },
    "2" : {
        "ORIGINE_LEAD" : "Formulaire Lead Add", 
        "SOURCE_LEAD" : "Olark Chat", 
        "NIVEAU_LEAD" : "Lead potentiel",
        "QUALITE_LEAD" : "Pourrait être pertinent", 
        "CONTACT_PAR_MAIL" : "Non", 
        "CONTACT_PAR_TELEPHONE" : "Non",
        "STATUT_ACTUEL" : "Sans emploi", 
        "NB_VISITES" : 0, 
        "DUREE_SUR_SITEWEB" : 0,
        "NB_PAGES_VUES_PAR_VISITE" : 0, 
        "DERNIERE_ACTIVITE" : "Email ouvert",
        "DERNIERE_ACTIVITE_NOTABLE" : "Select", 
        "PAYS" : "France", 
        "VILLE" : "Paris", 
        "SPECIALISATION" : "Marketing Management", 
        "TAGS" : "Ne pas suivre de formation continue",
        "INDEX_ACTIVITE" : "Moyen", 
        "INDEX_PROFIL" : "Moyen", 
        "SCORE_ACTIVITE" : 15.0, 
        "SCORE_PROFIL" : 15.0,
        "ANNONCE_VUE" : "Non", 
        "MAGAZINE" : "Non", 
        "ARTICLE_JOURNAL" : "Non", 
        "FORUM" : "Non", 
        "JOURNAUX" : "Non",
        "PUB_DIGITALE" : "Non", 
        "RECOMMANDATION" : "Non",
        "C_ENT_PARLER_NS" : "Non",
        "SOUH_TU_REC_INFOS" : "Non",
        "SOUH_REC_MAJ_PROG" : "Non",
        "SOUH_REC_MAJ_MP" : "Non",
        "SOUH_PAYER_CHEQUE" : "Non",
        "SOUH_REC_COPIE_LB" : "Non"
    }
}



