image: docker:latest
services:
  - docker:dind


stages:
  - build
  - deploy

build-docker-image:
  stage: build
  variables:
    IMAGE_NAME: eu.gcr.io/yotta-square-ml3/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH
  script:
  - echo "$GITLAB_IAM_PRIVATE_KEY" > key.json
  - docker build . -t $IMAGE_NAME
  - docker login -u _json_key -p "$(cat key.json)" $IMAGE_NAME
  - docker push $IMAGE_NAME


deploy to develop:
  stage: deploy
  image: google/cloud-sdk:257.0.0
  script:
    - echo "$GITLAB_IAM_PRIVATE_KEY" > key.json
    - gcloud auth activate-service-account --key-file key.json
    - gcloud config set project yotta-square-ml3 
    - gcloud config set compute/zone europe-west1-b 
    - gcloud container clusters get-credentials chaos-cluster 
    - kubectl apply -f deployment/example_pod_develop.yml
    - kubectl apply -f deployment/deployment-4.yml
    - kubectl apply -f deployment/load-balancer-4.yml

