apiVersion: apps/v1
kind: Deployment

metadata:
  name: deployment-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH
  labels:
    app: lead_scoring
    environment: $CI_COMMIT_BRANCH
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: lead_scoring
      environment: $CI_COMMIT_BRANCH
  
  template:
    metadata:
      labels:
        app: lead_scoring
    
    spec:
      containers:
      - name: lead_scoring_container
        image: eu.gcr.io/yotta-square-ml3/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH-$CI_COMMIT_SHA
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: secrets
          mountPath: "/secret"
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: chaos-secrets-4
