apiVersion: apps/v1
kind: Deployment

metadata:
  name: deployment-PROJECT_NAME-ENVIRONMENT
  labels:
    app: lead-scoring-app-ENVIRONMENT
spec:
  replicas: NB_REPLICAS
  selector:
    matchLabels:
      app: lead-scoring-app-ENVIRONMENT
  
  template:
    metadata:
      labels:
        app: lead-scoring-app-ENVIRONMENT
    
    spec:
      containers:
      - name: lead-scoring-app-ENVIRONMENT
        image: eu.gcr.io/yotta-square-ml3/PROJECT_NAME:ENVIRONMENT-TAG
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: volume-secrets-choas-4
          mountPath: "/secret/"
          readOnly: true
        env:
          - name: YOTTA_ML3_CONFIGURATION_PATH
            value: "/secret/config.yml"
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/secret/yotta-square-ml3-b58a21bd2576.json"

      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
        command:
          - "/cloud_sql_proxy"
          - "-instances=yotta-square-ml3:europe-west1:group-4=tcp:5432"
          - "-credential_file=/secret/yotta-square-ml3-b58a21bd2576.json"
        securityContext:
          runAsNonRoot: true
        volumeMounts:
        - name: volume-secrets-chaos-4
          mountPath: /secret
          readOnly: true
      volumes:
      - name: volume-secrets-chaos-4
        secret:
          secretName: chaos-secrets-4
