apiVersion: v1
kind: Service

metadata:
 name: load-balancer-PROJECT_NAME-ENVIRONMENT

spec:
 ports:
 - port: 80
   protocol: TCP
   targetPort: 5000
   nodePort: 7643
 selector:
   app: lead-scoring-app
 type: LoadBalancer
